FROM node:14.3.0-stretch-slim

# Create app directory
WORKDIR /usr/src/app

# Clone the skeleton project and install dependencies
RUN apt-get update && apt-get install -y git procps autoconf libtool make &&\
  git clone --branch codegen#140-refactor-search-input https://github.com/Zendro-dev/graphql-server.git . && \
  chmod u+x ./migrateDbAndStartServer.sh && \
  npm install --save

EXPOSE 3000
